version: 2
updates:
  - package-ecosystem: maven
    directories: [/order-processor, /config-server, /e2e/karate]
    schedule: { interval: weekly }
  - package-ecosystem: gomod
    directory: /products-api
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directories: [/clients-api, /order-tracker/e2e]
    schedule: { interval: weekly }
  - package-ecosystem: pub
    directory: /order-tracker
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directories: [/order-processor, /products-api, /clients-api, /order-tracker, /config-server]
    schedule: { interval: weekly }
  - package-ecosystem: docker-compose
    directory: /
    schedule: { interval: weekly }
