env:
  SEED_ENABLED: "false"
  KAFKA_TLS_ENABLED: "true"
  KAFKA_BOOTSTRAP_SERVERS: "b-1.msk.production.example.com:9094,\
    b-2.msk.production.example.com:9094,\
    b-3.msk.production.example.com:9094"
  CONFIG_PROFILE: production
  AUTH_ISSUER: https://auth.production.example.com/realms/mariposa
  AUTH_JWKS_URL: https://auth.production.example.com/realms/mariposa/protocol/openid-connect/certs
  APP_ENV: production
