image:
  repository: grupo-mariposa/products-api
containerPort: 8081
podSecurityContext:
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
env:
  PORT: "8081"
  AUTH_ENABLED: "true"
  AUTH_REQUIRED_ROLE: products-reader
  AUTH_AUDIENCE: products-api
  FAULT_INJECTION_ENABLED: "false"
  CONFIG_SERVER_URL: http://config-server.grupo-mariposa.svc.cluster.local
  CONFIG_APP_NAME: products-api
  CONFIG_SERVER_USERNAME: config-reader
  CONFIG_SERVER_FAIL_FAST: "true"
  KAFKA_TOPIC_CHANGES: products.changed.v1
externalSecret:
  enabled: true
  remoteKey: grupo-mariposa/products-api
  keys:
    - MONGODB_URI
    - secretKey: CONFIG_SERVER_PASSWORD
      remoteKey: grupo-mariposa/config-server
      property: CONFIG_SERVER_PASSWORD
networkPolicy:
  enabled: true
  allowedFrom:
    - order-processor
    - admin-tools
  allowedNamespaces:
    - operations
